### ISSUE TITLE
[RFC] - I want to ignore files when packaging mods

### ISSUE THREAD

**Issue by osulli** [WolvenKit/gpm#1]
## What

As a user, I would like to be able to ignore some file when publishing a mod package.

**Comment by marius851000** [comment]
Proposed solution:
have a .cpignore file that follow the same specification as .gitignore (https://git-scm.com/docs/gitignore . Didn't read them, just use a library that implement it).
potentially use .gitignore by default, but this would exclude compiled content, that we may want to include include in the mod. 
2 possibility:
- don't use .gitignore by default. User should link .gitignore to .cpignore
- add a ``--no-ignore`` flag to not use both .gitignore and .cpignore. .gitignore is ignored if .cpignore exist.

**Comment by Aelto** [comment]
What is proposed solution to include the .gitignore in the .cpignore? We agreed that `.cpignore` will always be used by default right? What about an optional parameter to also use the gitignore, something like `gpm publish --use-gitignore` could work, and it would mean that the CLI would use the gitignore instead of the cpignore (or both?)

**Comment by marius851000** [comment]
rather than a ``--use-gitignore``, maybe a ``--ignore-file <path>`` that use any specified ignore file rather than the .cpignore one. Maybe we could use some preprocessing to include a gitignore into another, but that seem to be uselessly complicated. Maybe adding a ``--no-ignore`` could be usefull, however.

**Comment by MythicManiac** [comment]
It was noted on Discord that assuming we want to turn the tool into a generic game package manager, we should probably stick to names that aren't related to cyberpunk.

Some proposals:
* `.gpmignore`
* `.modignore`

**Comment by marius851000** [comment]
Right now, it ignore file in the ``.modignore`` at the root of the mod, in the same format as gitignore, based on the crate ``ignore``.
