### ISSUE TITLE
Providing API Info for Schaken-Mods

### ISSUE THREAD

**Issue by Schaken** [WolvenKit/gpm#16]
I had briefly talked to @osulli on discord about a possible connection with your Mod manager and my website. I mentioned I am willing to make a donation and/or Contribution to the wonderful creators here. My website uses the "Invision Community" Framework and I have a rather vast setup of API info. I would love to discuss with someone what I may be able to offer, and get you all the information you need to make this a possibility

You can ping me on your Cyberpunk server as "@Schaken" or you can hunt me down at https://Schaken-ModsChat.com (Its a custom Discord Link is all) 

All API for my site can be found here: https://invisioncommunity.com/developers/rest-api/index/ 
I also have some created ones from some content creators.

**Comment by osulli** [comment]
Initially we would need the following information:

```
# cybermods.net example
identifier = "cybermods"
display_name = "Cybermods"
base_url = "https://cybermods.net/"
download_endpoint = "package/download/"
latest_version_endpoint = ""
file_types = ["zip"]
```

**Comment by Schaken** [comment]
identifier = "schakenmods"
display_name = "Schaken-Mods"
base_url = "https://schaken-mods.com/"
download_endpoint = "/downloads/files/{id}/download"
latest_version_endpoint = ""
file_types = ["zip, rar, 7z"]

I hope this will help.

**Comment by MythicManiac** [comment]
I think the responsibility of gpm compatibility is on the package registries, rather than needing gpm to be implicitly compatible with any and every registry. This means we should come up with a standard registry access API specification that any registry wishing to be compatible with the ecosystem can implement an interface to, and gpm should target compatibility with that specification. This is not unlike to how most/all other package managers function, npm, docker, pypi, or cargo just to name a few.

I've opened #17 for discussing what the registry API should look like and what guarantees it should offer. Would love to have you @Schaken join the discussion there.
